exp_name: exp1
checkpoints_dir: ./checkpoints/${exp_name}/${dataset.dataset_name}
log_path: 
resume:
only_test: False
hydra:
  run:
    dir: ./checkpoints/${exp_name}/${dataset.dataset_name}

defaults:
  - _self_
  - dataset: HumanML3D

preprocess:
  padding: true
  use_kinematic: true
  fps_aug: false
  shear: false

model:
  motion_encoder_ckpt: checkpoints/mola_stage2/HumanML3D/best_model.pt  #your path to pretrained model
  num_reg_tokens: 5
  projection_hidden_size: 2048
  lora_r: 16
  use_lora: True
  

train:
  batch_size: 128
  epoch: 50
  optimizer:
    motion_lr: 1.0e-05
    text_lr: 1.0e-05
    head_lr: 1.0e-05
  train_motion_encoder: true
  train_text_encoder: true
  motion_encoder_pretrained: true
  patch_size: 16
  part_weight: 0.5
  mix_weight: 0.5
  stage_weight: 0.3
  entropy_weight: 0.0
  order_weight: 0.1
  seed: 42 

eval:
  eval_train: false
  use_best_model: true